# Generated by Django 5.1.3 on 2024-11-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='text',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='text',
            name='link',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
