# Generated by Django 5.1.3 on 2024-11-28 18:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_rssfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
