# Generated by Django 5.1.3 on 2024-11-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0003_text_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='read_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
