# Generated by Django 5.1.3 on 2025-10-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0007_rssfeed_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='should_update',
            field=models.BooleanField(default=True),
        ),
    ]
