# Generated by Django 5.1.3 on 2025-10-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0008_rssfeed_should_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
